### PR TITLE
Image upload

### PR DESCRIPTION
**Pull request by ONourry**
Images are now stored only in the database (no more local files in docker container)
Modified database fields to accept base64 encoded strings

- ImageRoute get requests now returns base64 encoded strings of images instead of binary image files. These string will have to be decoded  in the frontend before displaying them.

- Post request behaviour has not changed from previously (accepts binary image file). Only the behaviour in the backend has changed (images are now encoded before being stored)

Spot get request now returns list of all images corresponding to spotId

Postman requests to test:
GET
Spot:  http://localhost:5000/upload/spot-image/12345
Profile: http://localhost:5000/upload/profile-image/12345

POST (Must include file in body. See picture in comment below)
Spot: http://localhost:5000/upload/spot-image/12345
Profile: http://localhost:5000/upload/profile-image/12345

### CODE REVIEW

**Comment by ONourry** [comment]
Screen Shot 2021-04-21 at 6 07 40 PM

**Review by ShimizuKazuki — COMMENTED** [review]
Can we post not only spot image, but also user iamge?

**Review by ShimizuKazuki — APPROVED** [review]
Don't worry, I checked user image

**Review by ShimizuKazuki — COMMENTED** [review]
I don't know why this one is commented out
```
#CMD ["npm","start"]
```

**Comment by ONourry** [comment]
That was for testing, I can add it back.

**Comment by ShimizuKazuki** [comment]
Then, please add it back.
I got some error because of it.

**Comment by ShimizuKazuki** [comment]
this branch was merged to Feature/abatar setting #147

**Pull request closed without merging**
